/**
 * Auto-generated version information for MAVSDK Drone Show
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by tools/version_sync.py
 *
 * To update the version:
 * 1. Edit the VERSION file in project root
 * 2. Run: python tools/version_sync.py
 * 3. Rebuild the frontend: npm run build
 */

const DEFAULT_VERSION = '5.1';
const DEFAULT_GIT_COMMIT = '5039e182';
const DEFAULT_GIT_BRANCH = 'main';

const VERSION = process.env.REACT_APP_VERSION || DEFAULT_VERSION;
const GIT_COMMIT = process.env.REACT_APP_GIT_COMMIT || DEFAULT_GIT_COMMIT;
const GIT_BRANCH = process.env.REACT_APP_GIT_BRANCH || DEFAULT_GIT_BRANCH;
const VERSION_DISPLAY = `v${VERSION} (${GIT_COMMIT})`;

export { VERSION, GIT_COMMIT, GIT_BRANCH, VERSION_DISPLAY };

const versionInfo = {
  VERSION,
  GIT_COMMIT,
  GIT_BRANCH,
  VERSION_DISPLAY
};

export default versionInfo;
